BuildCraft/BuildCraft

common/buildcraft/BuildCraftEnergy.java, common/buildcraft/energy/BlockBuildcraftFluid.java
Swimming upwards is pretty much impossible in Vanilla with this (some mods might make it possible).
Crude Oil is a very dense semifluid, you should not be able to swim properly in it; if you jump into an oil well, you will most likely die but that's your own fault then. Oil is deadly.
Also added a config option to restore previous behaviour.
=> Make swimming in oil a lot harder

.travis.yml
Option -S enables full stack trace logging which in case of Grovy is very obscure.
Default logging shows CheckStyle errors in console.
=> Make Travis builds logs less obscure.

common/buildcraft/transport/BlockGenericPipe.java
Make BlockGenericPipe use the IPipeTile to access Pipe and TileGenericPipe.
Allow non TGP implementation of IPipeTile to pass an internal version of Pipe.
=> Use IPipeTile insead of direct TGP access in BlockGenericPipe. [Make LP easier]

api/buildcraft/api/blueprints/SchematicBlock.java, api/buildcraft/api/blueprints/SchematicFluid.java, api/buildcraft/api/core/BuildCraftProperties.java, api/buildcraft/api/robots/ResourceId.java, common/buildcraft/core/BlockBuildCraft.java, common/buildcraft/core/BlockSpring.java, common/buildcraft/energy/BlockEngine.java, common/buildcraft/silicon/BlockLaserTable.java, common/buildcraft/transport/BlockGenericPipe.java
The API package mustn't depend on the core, in order or it to be independent.
To do that, I extracted some methods from Utils, and moved the Block Property declarations to a new class in the API, so classes in the API, and addon mods too, can use them.
=> Wix API-core dependencies

common/buildcraft/core/lib/render/FluidRenderer.java
Tanks will display as at least 1/100 full, even if they have less.
=> fix Z-fighting on almost empty tanks

common/buildcraft/core/lib/block/BlockBuildCraft.java
Since the wrench (and other mods' wrenches as well) already rotate the block upon use, the rotation code is not needed in onBlockActivated and would end up rotating the block twice on the client.
=> fix blocks being rotated twice on the client

common/buildcraft/core/lib/gui/GuiBuildCraft.java
The check for `isMouseOver` in `GuiBuildCraft.mouseClicked` offsets mouseX and mouseY by guiLeft and guiTop.
The check for `isMouseOver` in `GuiBuildCraft.drawScreen` should do the same thing.
This is because Widget coordinates are relative to the Gui, not the Screen.
To make the tooltip appear, you have to move your mouse way far away right now.
Cheers :bee:
=> Gui Widget tooltips don't draw

common/buildcraft/transport/FacadePluggable.java, common/buildcraft/transport/render/FacadeRenderHelper.java
Facades rendered on LP pipes are always invisible without this change.
This does not change anything on BC internals as `PipeRendererWorld.renderPass` is the same that is used to call the function anyway, but until now it was ignored.
=> Actually use the render pass parameter - Fixes API calls that use renderPluggable with facades

common/buildcraft/builders/LibraryDatabase.java
When a template specifies an extension that is not of length 3 (such as the default `tpl` and `bpt` ones), loading the list currently generates broken entries, because the `uniqueId` is built assuming the extension length is always 3. The result is that such entries can neither be loaded nor deleted. This change should properly allow for arbitrary file extension lengths. (I say should, but I built it and tested it, and it worked).
=> Fixes handling of template extensions length != 3.

common/buildcraft/core/properties/WorldPropertyIsOre.java
Modified the ore check to check against what is actually dropped by the ore rather than the block itself.  This should fix almost any tile entity based ore.
Considerations:
getDrops() can be slightly slower than ItemStack(block, 1, meta) though in most cases should be unnoticeable.
=> Make mining robots work with gregtech ores

common/buildcraft/builders/BlockArchitect.java, common/buildcraft/builders/TileArchitect.java, common/buildcraft/transport/utils/FluidRenderData.java
-Removed unused field on BlockArchitect
-Architect table area box not being visible from far away. It now uses the same render distance as the Builder. Closes #2921
-Use FluidStack sensitive version of Fluid.getLuminosity()
=> Architect table render distance fix + other tweaks

common/buildcraft/core/blueprints/BptBuilderBlueprint.java
BptBuilderBlueprint.checkRequirements expects an exact match, but
BptBuilderBlueprint.useRequirements will accept ore-dictionary (and
other?) equivalent items.
=> Fix builder inconsistently respecting OreDict

common/buildcraft/BuildCraftBuilders.java, common/buildcraft/BuildCraftCore.java, common/buildcraft/BuildCraftFactory.java, common/buildcraft/BuildCraftRobotics.java, common/buildcraft/BuildCraftSilicon.java, common/buildcraft/BuildCraftTransport.java
Chests and crafting tables were registered in Ore Dictionary to support Wood Stuff mod by ganymedes01. I've decided to make a PR for 7.0.x branch instead of 7.1.x since 7.1.x still in Beta and there are no ETA when it's out from Beta. I've tested this in-game and didn't found any issues, so it's shouldn't hurt anything. (I know very little about coding mods, so I'm not sure that I've put OreDictionary.registerOre strings into correct place but at least it works)
=> More Ore Dictionary support for recipes

misc/dist.sh
Adds square brackets at the beginning and end of the modules mcmod.info file.
This fixes issue #3034.
Sorry I didn't notice this issue sooner.
=> Fix mcmod.info

common/buildcraft/factory/BlockTank.java
The side texturing logic for the block is specifically looking for 'this' block instead of looking more generically if the block is an instance of BlockTank which means blocks extended from BlockTank do not render correctly when mixed. 
This brings the graphical portion of the BlockTank in-line with the way the TileTank actually works (checking instanceof when moving up and down a stack, not 'this').
=> Improve tank texturing logic

common/buildcraft/BuildCraftBuilders.java, common/buildcraft/builders/schematics/SchematicTripwire.java
The builder was using BlockFloored for the tripwire(string), but tripwires can be placed in the air without a supporting block - this allows this behaviour.
=> Allow builders to place floating tripwires

common/buildcraft/transport/render/PipeTransportFluidsRenderer.java
Simply checks if pipe.container is null before continuing.
=> Fixed issue #3134.

common/buildcraft/transport/PipeTransportItems.java
Fixes: Item pipes don't work properly AlexIIL/Buildcraft_1.8_Issues#55
Can't see the need to multiply by item speed, as is already comparing the base container and travelling item positions.
=> middleReached never true on Item Transport Pipes

common/buildcraft/BuildCraftRobotics.java, common/buildcraft/core/tablet/manager/TabletManagerClient.java, common/buildcraft/core/tablet/manager/TabletManagerServer.java
Seeing Thread-xx in thread dumps isn't great.
=> Add thread names for Robotics/Tablet manager

common/buildcraft/silicon/render/RenderLaserTile.java
@AlexIIL what you think of it? (Hoping that it'll do it into 7.2.7 :D)
Current State:
Appearence after this pull request:
And if you've installed shaders the difference is even bigger:
to
=> Adding some neat lighting effects for the laser (some sort of glowing, virtually)

common/buildcraft/energy/container/ContainerEngineStone_BC8.java, common/buildcraft/factory/tile/TileAutoWorkbenchBase.java, common/buildcraft/lib/gui/ContainerBC_Neptune.java
I think I fixed the crashes caused by Shift-Clinking in any BC Container.
The crash is caused by the slotClick() function ofnet.minecraft.inventory.Container
which calls transferStackInSlot(). ContainerBC_Neptune didn't override this method, the default implementation was called which basicly does nothing. After this, slotClick() checks whether the transfer was successful and retrys if not. Since the transfer didn't happen it falls into an infinite loop and crashes.
ContainerEngineStone_BC8 still crashed because it only checked if an item is valid for a slot when it was already being inserted ( see ItemHandlerSimple, setStackInSlot() ) so I added isValidItem() to it's SlotBase implementation.
=> Fixed Shift-Click crash (#3479)

common/buildcraft/transport/Gate.java
Fix a crash when a Thermal Expansion Autonomous Activator clicks on a BuildCraft gate.
=> Fix a crash when a machine "clicks" on a gate

common/buildcraft/energy/generation/OilPopulate.java
base problem was a check that got inverted, also some extra checks for if a block is replacable, tendrills spill into nearby chunks that have not generated yet so the first block(s) eighter return air or flowing water while the generator realises the chunk has not been generated and interups the oil spilage to generate the new chunk
=> fix oil tendrill generation (#3601)

common/buildcraft/factory/tile/TileTank.java
Adding a check for quantity of items. If there are more than one item try to use one item from the stack. If item from the stack is filled `give it to the player or drop it at their feet` as is done in core forge.
Closes #3729
=> 3729: fixing handling of stacked fluid container by tank

common/buildcraft/core/item/ItemPaintbrush_BC8.java
Fixed issue #3834 , fixed the issue by checking if the player holding the brush is in creative mode, if he is then there is no change to the brush's durability.
=> Fixed paintbrush getting damaged in creative

common/buildcraft/factory/client/model/ModelHeatExchange.java, common/buildcraft/lib/client/model/ModelItemSimple.java
Updated ModelHeatExchange to make sure the particle is always set from the quads in the constructor rather than staying null. #3874
=> Set particle for ModelHeatExchange

common/buildcraft/transport/pipe/behaviour/PipeBehaviourObsidian.java
As per #3884 obsidian pipes that were not connected to any other pipes caused a crash as they had nowhere to send items to.
To fix this, if there are no pipes to send items to then the obsidian pipes don't try to suck items and don't draw power (as they cannot function)
=> Obsidian pipes no longer draw power when not connected to other pipes

common/buildcraft/core/BCCoreConfig.java, common/buildcraft/factory/tile/TilePump.java
I decided to add this option for myself since I wanted to drain an Ocean Monument using a bunch of pumps around the perimeter and a finite water mod - it makes this possible but has a huge effect on performance when increased much above 64 as you might expect. If you don't want to merge this I'll just maintain my own fork 😄
=> Add a config option to change the max water pumping distance.

common/buildcraft/transport/block/BlockPipeHolder.java, common/buildcraft/transport/plug/FacadeBlockStateInfo.java, common/buildcraft/transport/plug/FacadeInstance.java, common/buildcraft/transport/plug/FacadePhasedState.java, common/buildcraft/transport/plug/PluggableFacade.java
Fixes https://github.com/BuildCraft/BuildCraft/issues/3994.
Also changed hollow facades to be considered as not solid.
=> Fixed facades returning BlockFaceShape.UNDEFINED when they shouldn't

common/buildcraft/factory/tile/TileTank.java
Tanks are currently implicitly associated when they're stacked together. This PR allows tanks to also be explicitly associated through an association key provided on the tile. 
The purpose of this is to allow third party add-ons (like Iron Tanks) to explicitly define and track an association key for their own tanks and control what tanks can pass fluid down (or up) the stack. 
Current implementation leaves association key for all Buildcraft tanks set to NULL, so no change in current behavior, any stacked set of tanks will allow fluid/gas flow between the tanks in the stack. 
Specific use case is for Iron Tanks Creative and Void tanks which should not stack with any other tanks. 
Potential future use case could include stained glass tanks which don't allow fluid flow between different …
=> Allow tanks to be explicitly associated

common/buildcraft/lib/client/guide/loader/entry/ItemStackValueFilter.java
Right now if a stack wants just meta sensitivity it gets only NBT instead, and vice versa. This causes page misses in the guide book from comparing the wrong properties.
The actual logic is sound, it's just the [constructor args](https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/lib/client/guide/loader/entry/ItemStackValueFilter.java#L13) in ItemStackValueFilter are opposite to the order passed in by [EntryTypeItem](https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/lib/client/guide/loader/entry/EntryTypeItem.java#L50).
=> Fix complex stacks meta vs NBT comparison

common/buildcraft/factory/client/render/RenderTank.java
Added a check when determining `connectedUp` & `connectedDown` to ensure that tanks are only 'connectedUp/Down' when the tanks being checked are allowed to be connected. 
fixes #4031
=> Fix fluid rendering for tanks which cannot stack

buildcraft_resources/changelog/7.99.17, common/buildcraft/factory/tile/TileMiningWell.java
The code follows the same pattern as the code for the Quarry.
I tested this in-game for both lava, a fuel, and no liquid, confirming expected behavior (stops when a fluid is present)
=> Fix #4082 - Fluids can no longer be broken by Mining Well

buildcraft_resources/changelog/7.99.17, common/buildcraft/energy/BCEnergyConfig.java, common/buildcraft/energy/generation/OilGenerator.java
* Ported option to disable generation of oil spout.
* Ported option to change rate of occurrence of large oil wells.
These are literal ports of the old code. I do not like very much that "rate" is not really a rate of how often a oil well appears, but how likely it is for them to be larger. I think that that is fine as a port, but I definitely support a new issue to improve how oil is generated and what quantities of it should be part of the config, as per #3966. I haven't addressed #3966 because of that.
=> Fix #4080 - Ported option to disable generation of oil spout and change rate of occurrence of large oil wells

buildcraft_resources/changelog/7.99.17, common/buildcraft/factory/tile/TileHeatExchange.java
This allows the Heat Exchanger to receive multiples of 5, which allows to process every combination of fluids from the distiller.
Also removed the multiplier non-divisible by 1000 that was in contradiction to the comment.
af7743f is about allowing the HE to process multiple multiples. E.g. a 3-middle section HE can now process 10 units of liquid if it accepts it.
=> Improvements to Heat Exchanger code

common/buildcraft/factory/tile/TileTank.java
the getTankProperties method previously did not account for gasseous liquids, which end up in the top tank.  The function now also checks the top tank in case there is gasseous liquid in it.  It appears this fixes #4133.
=> changed getTankProperties to test for fluid on top

common/buildcraft/transport/BCTransportSprites.java, common/buildcraft/transport/BCTransportStatements.java, common/buildcraft/transport/pipe/flow/PipeFlowPower.java, common/buildcraft/transport/statements/TriggerPowerRequested.java, common/buildcraft/transport/statements/TriggerProviderPipes.java
Trigger turns on when requested power is more than 1 MJ.
=> Add Power Requested trigger

common/buildcraft/builders/tile/TileFiller.java
Game doesn't crash anymore, when gate sets filler pattern
=> Fix #4407 - Minecraft doesn't crash anymore when gate sets filler pattern

common/buildcraft/lib/script/SimpleScript.java, sub_projects/expression/src/main/java/buildcraft/lib/expression/api/NodeTypes.java
I fixed the main issues in the Javadoc, caused by malformed HTML code, which lead to build errors
=> Fixed Javadoc build errors

common/buildcraft/transport/pipe/flow/PipeFlowFluids.java
FIXES a bug where accesing lastSentDirection.nbtValue throws a NullPointerException when placing a wooden fluid pipe next to a Magneticraft Infinite Water block and then breaking wooden fluid pipe. To the best of my Java ability I couldn't figure out why :(
=> Fix NullPointerException crash in PipeFlowFluids

build.gradle, common/buildcraft/core/recipes/FlexibleRecipe.java
Affects `buildcraft.core.recipes.FlexibleRecipe#setContents()`.
This change is backwardscompatible and fullfills this promise:
I was not able to build the jars, even with a fresh clone. It always crashes at `:javadoc`. Maybe this [log](https://gist.github.com/glowredman/59c3fbd6c1fe1cb963c22b5a69c92177) of `gradlew build --stacktrace --info --debug` can help with that...
When I removed the javadoc tasks, after that, it built as expected.
=> Allow oredicted ItemStacks with stacksizes greater than 1
