api/buildcraft/api/recipes/IFlexibleRecipeViewable.java
api/buildcraft/api/statements/IStatement.java
api/buildcraft/api/statements/IStatementParameter.java
common/buildcraft/core/utils/MatrixTranformations.java
common/buildcraft/energy/BlockBuildcraftFluid.java

In Java8 JavaDoc has to be correct XML document.
Edit: And fixed CheckStyle.

Fix JavaDoc for Java8 compability

---

common/buildcraft/core/robots/DockingStation.java
common/buildcraft/core/robots/EntityRobot.java

Fixes this http://mod-buildcraft.com/forums/index.php?topic=3286.0

fix docking stations staying linked when changing a robot's main link

---

common/buildcraft/BuildCraftTransport.java
common/buildcraft/transport/ItemFacade.java

The pipe sealant recipe is useful if there is no desert nearby. It was approved by SpaceToad on the BC forums.
Facade change prevents facades being created for odd things like levers.

Additional pipe sealant recipe and facade change

---

common/buildcraft/robots/ai/AIRobotFetchItem.java

Signed-off-by: Kubuxu <kubuxu@gmail.com>

Fix picker robots dancing if two items are in same block

---

common/buildcraft/robots/boards/BoardRobotKnight.java

Also the knight now attack Angry Wolf

Knights now search IMob instead of EntityMob (Fix #2537)

---

common/buildcraft/energy/TileEngineIron.java

Now no coolant is lost due to rounding, and coolants that are too strong will not cause engines to blow up before even being used.

Add a cooling buffer, fix #2530

---

common/buildcraft/factory/TileRefinery.java

Works in theory, not that I can reproduce the bugs.

Should fix #2541

---

common/buildcraft/BuildCraftTransport.java

Someone copy-pasted and didn't change everything they needed to...

Slimeballs don't have meta

---

common/buildcraft/silicon/BlockLaser.java

Fix for https://github.com/BuildCraft/BuildCraft/issues/2582.

Fix #2582.

---

api/buildcraft/api/crops/CropManager.java
api/buildcraft/api/crops/ICropHandler.java
common/buildcraft/BuildCraftCore.java
common/buildcraft/BuildCraftRobotics.java
common/buildcraft/core/crops/CropHandlerPlantable.java
common/buildcraft/core/crops/CropHandlerReeds.java
common/buildcraft/core/lib/utils/BlockUtils.java
common/buildcraft/core/properties/WorldPropertyIsHarvestable.java
common/buildcraft/robotics/ai/AIRobotHarvest.java
common/buildcraft/robotics/boards/BoardRobotGenericBreakBlock.java
common/buildcraft/robotics/boards/BoardRobotGenericSearchBlock.java
common/buildcraft/robotics/boards/BoardRobotHarvester.java
common/buildcraft/robotics/boards/BoardRobotPlanter.java

Extracted the crop handling code from robots, should make it easy for stripes pipes to be able to plant/harvest crops. I think the api should be able to support any mods with special methods for farming.

add crop api

---

common/buildcraft/BuildCraftBuilders.java

Corrected config comment on `doChunkLoading`.

---

common/buildcraft/BuildCraftTransport.java

Writing "color" so many times was very painful.

Use colourless glass in pipe's recipes

---

api/buildcraft/api/robots/ResourceId.java
common/buildcraft/builders/BlockMarker.java
common/buildcraft/builders/RenderArchitect.java
common/buildcraft/builders/RenderConstructionMarker.java
common/buildcraft/builders/TileBuilder.java
common/buildcraft/builders/TileQuarry.java
common/buildcraft/core/blueprints/BptBuilderBase.java
common/buildcraft/core/blueprints/SchematicRegistry.java
common/buildcraft/core/config/ConfigManager.java
common/buildcraft/core/lib/engines/TileEngineBase.java
common/buildcraft/core/recipes/RefineryRecipeManager.java
common/buildcraft/core/render/RenderBuilder.java
common/buildcraft/energy/TileEngineIron.java
common/buildcraft/robotics/EntityRobot.java
common/buildcraft/robotics/StationIndex.java
common/buildcraft/silicon/TileLaser.java
common/buildcraft/transport/BlockGenericPipe.java
common/buildcraft/transport/PipeTransportFluids.java
common/buildcraft/transport/pipes/PipeFluidsWood.java
common/buildcraft/transport/pipes/PipePowerEmerald.java
common/buildcraft/transport/pipes/PipePowerWood.java

Fix bugs and remove unnecessary nullchecks.

---

guidelines/buildcraft.checkstyle

It will prevent accidental leaves of debug messages in relase.

Add System.out/err to checkstyle as errors

---

common/buildcraft/factory/TileFloodGate.java

They seem pointless and spam console constantly on public servers

Removed debug messages in the flood gate

---

common/buildcraft/transport/pipes/PipeItemsEmerald.java

Only extract items if there is energy

---

README.md

it had the link to what used to be the sugestions board. Also the sentence was cut off

update readme with new forumboard link

---

common/buildcraft/BuildCraftCore.java
common/buildcraft/core/lib/utils/PathFinding.java
common/buildcraft/core/properties/WorldPropertyIsFreePath.java
common/buildcraft/robotics/ai/AIRobotFetchItem.java
common/buildcraft/robotics/ai/AIRobotGotoBlock.java

a) blocks without boundingbox can now be in a path
b) Robots (picker) can now pickup items one block away (if block has a bounding
box)
c) robots shouldn't be stuck due to path changes anymore (hopefully recalculates path)

fixes #3311

---

Jenkinsfile

I've added a Jenkinsfile for automatic builds on a new 2.x jenkins.
Here's the PR for that if you want to use such a feature again.
Jenkins only needs the "Docker pipeline" plugin. Node should also be configured to run docker containers. (Otherwise one has to remove the "withDockerContainer"-block)
Best combined with "GitHub Organization Folder Plugin",  then you can set up a "GitHub Organization Pipeline"-Project. 
All PRs and Branches are then build automatically if they have a Jenkinsfile.
Hope its helpful ;-)

Create/Add Jenkinsfile for Automatic Builds

---

common/buildcraft/lib/client/guide/parts/recipe/GuideAssemblyRecipes.java
common/buildcraft/lib/inventory/filter/ArrayStackFilter.java
common/buildcraft/lib/inventory/filter/OreStackFilter.java
common/buildcraft/lib/misc/StackUtil.java
common/buildcraft/lib/recipe/AssemblyRecipeRegistry.java
common/buildcraft/lib/recipe/IntegrationRecipeRegistry.java
common/buildcraft/silicon/BCSiliconRecipes.java
common/buildcraft/silicon/tile/TileAssemblyTable.java
common/buildcraft/silicon/tile/TileIntegrationTable.java
common/buildcraft/silicon/tile/TileLaserTableBase.java
common/buildcraft/transport/BCTransportRecipes.java
common/buildcraft/transport/recipe/FacadeAssemblyRecipes.java

Switch to oredict recipes for assembly and integration tables.

---

common/buildcraft/core/statements/ActionRedstoneOutput.java
common/buildcraft/transport/block/BlockPipeHolder.java
common/buildcraft/transport/plug/PluggableGate.java
common/buildcraft/transport/tile/TilePipeHolder.java

make gates emit redstone again

---

common/buildcraft/transport/client/render/PipeFlowRendererPower.java
common/buildcraft/transport/pipe/flow/PipeFlowPower.java

no more packet spam and throughput isn't unlimited anymore

fix kinesis pipes

---

common/buildcraft/energy/generation/GenLayerAddOilDesert.java
common/buildcraft/energy/generation/GenLayerAddOilOcean.java
common/buildcraft/energy/generation/OilGenStructure.java
common/buildcraft/energy/generation/OilGenerator.java
common/buildcraft/energy/generation/OilPopulate.java
common/buildcraft/factory/tile/TileMiner.java
common/buildcraft/factory/tile/TilePump.java
common/buildcraft/factory/util/IAutoCraft.java
common/buildcraft/lib/engine/TileEngineBase_BC8.java
common/buildcraft/silicon/tile/TileAdvancedCraftingTable.java
common/buildcraft/silicon/tile/TileAssemblyTable.java
common/buildcraft/transport/block/BlockPipeHolder.java

backports some of the fixes i did while working on 1.12

Backport fixes

---

common/buildcraft/silicon/BCSilicon.java
common/buildcraft/silicon/BCSiliconConfig.java
common/buildcraft/silicon/client/render/RenderLaser.java

[Invisible Lasers](https://github.com/BuildCraft/BuildCraft/issues/3513) implemented via configuration option. Currently in the experimental configuration category, but that is subject to change once a proper place is figured out and the ability to view invisible lasers with goggles is implemented

Invisible Lasers

---

common/buildcraft/silicon/tile/TileLaser.java

- Laser only sends packet on target change 
- Laser beam position calculated on client side

Laser networking optimizations

---

common/buildcraft/builders/tile/TileQuarry.java

Video with new behavior [here](https://youtu.be/dV9wdlfS18c)

Fix quarry behavior, fixes #3740, fixes #3765 and fixes #3776

---

common/buildcraft/core/item/ItemList_BC8.java
common/buildcraft/transport/pipe/flow/PipeFlowFluids.java
common/buildcraft/transport/plug/FacadeStateManager.java

Shouldn't have force pushed these off the tree, these were good...

8.0.x temp

---

README.md

It took me a little while to find my artifacts, I'm assuming I'm not the only new person trying out the mod before it goes to release.

Update path to artifacts after successful build.

---

common/buildcraft/lib/block/BlockBCBase_Neptune.java
common/buildcraft/lib/block/VanillaRotationHandlers.java

I copied some vanilla logic to really find all valid rotations

Add missing vanilla rotation handlers, closes #4068

---

common/buildcraft/energy/BCEnergyConfig.java
common/buildcraft/energy/BCEnergyFluids.java
common/buildcraft/energy/generation/OilGenStructure.java
common/buildcraft/energy/generation/OilGenerator.java

More oil config options.
